services:
  - type: web
    name: tennis-stats-api
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
